from .user_type import UserType
from .genre import Genre
from .person import Person
from .user import User
from .email import Email
from .film import Film
from .character import Character
from .film_genre import FilmGenre
from .character_actor import CharacterActor
from .user_favourite_film import UserFavouriteFilm
